### PR TITLE
Cleanup + New System

### PR DESCRIPTION
**Pull request by TheOceanBreeze**
Here is the new system I suggest for Cssheet.

### CODE REVIEW

**Comment by ghost** [comment]
More explanation needed. What has specifically changed and I want more information as to what the new "system" is?

**Comment by TheOceanBreeze** [comment]
> new system

Basically, everything is now organized into separate files and the css can be minified, with the cost of using some SASS code and some cool node features.

**Comment by ghost** [comment]
Has the README.md been updated to inform the user on how to plug CSSheet into their website?

**Comment by TheOceanBreeze** [comment]
> Has the README.md been updated to inform the user on how to plug CSSheet into their website?

As far as just plugging the CSS, yes. Everything on the user's end should stay the same as long as we compile before updating.

**Comment by ghost** [comment]
Okay great. Can you run me through how to compile?

**Comment by TheOceanBreeze** [comment]
It's very easy. Just run ```npm run compile``` and you'll have yourself a fresh compiled version. Do ```npm run minify``` to minify the results. (Note you have to do ```npm install``` first when you first download the git repo, as it contains node stuff.)

**Comment by ghost** [comment]
Alright, thank you! I'll take a further look when I am home. 
Many thanks!

**Comment by TheOceanBreeze** [comment]
What do you think? Should we merge this?

**Comment by ghost** [comment]
Yep, it's your choice now that you're the Lead!

**Pull request merged**
